name: deploy ec2 nginx at aws
on:
  push:
    branches:
      - 'main'
jobs:
  deploy_ec2:
    name: deploy ec2 nginx at aws
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ARN_ROLE }}
          aws-region: ${{ secrets.REGION }}
        env:
          ARN_ROLE: ${{ secrets.ARN_ROLE }}
          aws-region: ${{ secrets.REGION }}
      - run: pip install -r requirements.txt
      - uses: pulumi/actions@v4
        with:
          command: preview
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - uses: pulumi/actions@v4
        with:
          command: up
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Sleep for 5 minutes
        run: sleep 300s
        shell: bash
      - uses: pulumi/actions@v4
        with:
          command: destroy
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
