name: deploy ec2 nginx at aws
on:
  push:
    branches:
      - 'main'
jobs:
  deploy_ec2:
    name: deploy ec2 nginx at aws
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.ARN_ROLE}}
          aws-region: ap-southeast-1
      - run: pip install -r requirements.txt
      - uses: pulumi/actions@v4
        with:
          command: preview
          stack-name: ${{env.STACK}}
        env:
          PULUMI_ACCESS_TOKEN: ${{secrets.PULUMI_ACCESS_TOKEN}}
          STACK: ${{env.STACK}}
      - uses: pulumi/actions@v4
        with:
          command: up
          stack-name: ${{env.STACK}}
        env:
          PULUMI_ACCESS_TOKEN: ${{secrets.PULUMI_ACCESS_TOKEN}}
          STACK: ${{env.STACK}}
      - name: Sleep for 5 minutes
        run: sleep 300s
        shell: bash
      - uses: pulumi/actions@v4
        with:
          command: destroy
          stack-name: ${{env.STACK}}
        env:
          PULUMI_ACCESS_TOKEN: ${{secrets.PULUMI_ACCESS_TOKEN}}
          STACK: ${{env.STACK}}
