name: deploy ec2 nginx at aws
on:
  push:
    branches:
      - 'main'
jobs:
  deploy_ec2:
    name: deploy ec2 nginx at aws
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.ARN_ROLE}}
          aws-region: ap-southeast-1
      - run: pip install -r requirements.txt
      # - uses: pulumi/actions@v4
      #   with:
      #     command: preview
      #     stack-name: ${{vars.STACK}}
      #   env:
      #     PULUMI_ACCESS_TOKEN: ${{secrets.PULUMI_ACCESS_TOKEN}}
      #     PUBLIC_KEY: ${{secrets.PUBLIC_KEY}}
      - uses: pulumi/actions@v4
        with:
          command: up
          stack-name: ${{vars.STACK}}
        env:
          PULUMI_ACCESS_TOKEN: ${{secrets.PULUMI_ACCESS_TOKEN}}
          PUBLIC_KEY: ${{secrets.PUBLIC_KEY}}
      - name: test curl ip
        env:
          URL: "http://${{ steps.pulumi.outputs.public_ip }}"
        run: |
          CODE=`curl -s -o /dev/null $URL --write %{stdout}`
          if [[ $CODE!="200" ]]
          then
            echo "FAILED"
          else
            echo "SUCCESS"
          fi

      - name: Sleep for 1 minutes
        run: sleep 60s
        shell: bash
      - uses: pulumi/actions@v4
        with:
          command: destroy
          stack-name: ${{vars.STACK}}
        env:
          PULUMI_ACCESS_TOKEN: ${{secrets.PULUMI_ACCESS_TOKEN}}
          PUBLIC_KEY: ${{secrets.PUBLIC_KEY}}
